Update jinja2 (major version)
The old version was causing the error
`ImportError: cannot import name 'soft_unicode' from 'markupsafe'`
because it was not pinned to a specific markupsafe version, jinja2 did
not specify an upper bound and the latest markupsafe removed
`soft_unicode`, which is used by jinja2<3.1. See also
https://github.com/pallets/markupsafe/issues/286.